[feat/#23] 회원가입 기능 추가
team-final/albaform pull request #154
Opened 2024-10-04 08:54 UTC by JiinSeok

resolved: #ISSUE_NUMBER

# 설명
- 회원가입을 원래 1개 페이지에서 버튼만 다르게 해서 '지원자로 회원가입', '사장님으로 회원가입'을 하고 싶었는데, 고민이 좀 필요할 것 같아서 일단 라디오 형식으로 구현했습니다.
- 회원가입 후 정보입력하는 페이지를 합쳤습니다. 2개 페이지가 상당히 유사해서 input만 분기하고 한번에 만들어도 되지 않을까 싶었습니다.
- 서버 500 에러가 발생하고 있어서 사장님 회원가입은 확인하지 못했습니다
- 모든 종류의 인풋이 Form 컴포넌트 파일 안에 들어있어서 놀라운 한편, Form 컴포넌트를 결국 쓰기 위해서는 방대한 코드를 이해해야 해서 컴포넌트 설계를 잘못한 걸까 하는 생각이 들었습니다. register 함수만 쉽게 쓰도록 훅이나 유틸함수 같은 걸로 간결화하고, Form 컴파운드 패턴을 컴포넌트 디렉토리 구조로 구현을 할 수도 있을 것 같습니다.
- 빌드 에러가 api에 있는 location이 브라우저 객체를 가리키는 것으로 이해돼서 발생하는 것 같은데 확인 부탁 드립니다..

```
  ▲ Next.js 14.2.10
  - Environments: .env.local

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
   Generating static pages (0/12)  [=   ]EXAMPLE_REQ_BODY:  {
  title: 'string',
  description: 'string',
  recruitmentStartDate: '2024-09-30T20:54:01.317Z',
  recruitmentEndDate: '2024-09-30T20:54:01.317Z',
  imageUrls: [ 'string' ],
  numberOfPositions: 0,
  gender: 'string',
  education: 'string',
  age: 'string',
  preferred: 'string',
  location: 'string',
  workStartDate: '2024-09-30T20:54:01.317Z',
  workEndDate: '2024-09-30T20:54:01.317Z',
  workStartTime: 'string',
  workEndTime: 'string',
  workDays: [ 'string' ],
  hourlyWage: 0,
  isPublic: true
}
ReferenceError: location is not defined
    at 28550 (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/app/user/sign-up/complete/page.js:1:18019)
    at t (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/webpack-runtime.js:1:128)
    at 7853 (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/app/user/sign-up/complete/page.js:1:7092)
    at t (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/webpack-runtime.js:1:128)
    at 96239 (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/app/user/sign-up/complete/page.js:1:2798)
    at t (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/webpack-runtime.js:1:128)
    at 43341 (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/app/user/sign-up/complete/page.js:1:93178)
    at Object.t [as require] (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/webpack-runtime.js:1:128)
    at require (/Users/jiin.seok/Documents/GitHub/albaform/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:18142)
    at a (/Users/jiin.seok/Documents/GitHub/albaform/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:88294) {
  digest: '335149951'
}

Error occurred prerendering page "/user/sign-up/complete". Read more: https://nextjs.org/docs/messages/prerender-error

ReferenceError: location is not defined
    at 28550 (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/app/user/sign-up/complete/page.js:1:18019)
    at t (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/webpack-runtime.js:1:128)
    at 7853 (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/app/user/sign-up/complete/page.js:1:7092)
    at t (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/webpack-runtime.js:1:128)
    at 96239 (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/app/user/sign-up/complete/page.js:1:2798)
    at t (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/webpack-runtime.js:1:128)
    at 43341 (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/app/user/sign-up/complete/page.js:1:93178)
    at Object.t [as require] (/Users/jiin.seok/Documents/GitHub/albaform/.next/server/webpack-runtime.js:1:128)
    at require (/Users/jiin.seok/Documents/GitHub/albaform/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:18142)
    at a (/Users/jiin.seok/Documents/GitHub/albaform/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:88294)
 ✓ Generating static pages (12/12)

> Export encountered errors on following paths:
        /user/sign-up/complete/page: /user/sign-up/complete
```

2024-10-04 14:48 UTC, gayeong0916 approved these changes

2024-10-04 15:40 UTC, JuhyeokC requested changes
코멘트
* A(https://github.com/team-final/albaform/pull/154#discussion_r1787876186)
* B(https://github.com/team-final/albaform/pull/154#discussion_r1787883805),
* C(https://github.com/team-final/albaform/pull/154#discussion_r1787883989)

모듈 CSS 를 선언하는 방식이 제각각입니다.
https://create-react-app.dev/docs/adding-a-css-modules-stylesheet/#buttonjs
위 create-react-app 문서에서 제시하는 `styles` 를 기본으로 하고
다른 디렉토리의 CSS 를 import 할 땐 앞에 주제를 붙여 `UserStyles` 혹은 `userStyles` 처럼 차이를 두는 건 어떠신가요?

2024-10-06 14:32 UTC, JiinSeok commented on src/app/user/sign-up/complete/page.module.scss
아이고 그러네요

2024-10-06 14:38 UTC, JiinSeok commented on src/components/Form/Form.tsx
> +      disabled={!isValid || isSubmitting || isPending}
isSubmitting처럼 상태에 따라서 disabled를 하고 싶은데 폼 제출의 상태 말고 네트워크 상태는 그 네트워크 함수를 쓰는 곳에서 정의하니까 그곳에서 프롭으로 내려줘야 했습니다.

signIn의 isPending을 내려주는 모습입니다. 
프롭 이름이 약간 헷갈릴 수 있다고는 생각했는데 안 떠올랐어요
```
          <Form.SubmitButton buttonStyle={'solid'} isPending={signIn.isPending}>
            {signIn.isPending ? '로그인 중...' : '로그인'}
          </Form.SubmitButton>
```

2024-10-06 15:11 UTC, JiinSeok commented on src/app/user/sign-up/complete/page.module.scss
@JuhyeokC 수정했습니다~ [`14b88d1` (#154)](https://github.com/team-final/albaform/pull/154/commits/14b88d152c22c2a4fb4af44447f595e36189cd90)

2024-10-06 15:39 UTC, JuhyeokC approved these changes

2024-10-06 15:39 UTC, JuhyeokC commented on src/app/user/sign-up/complete/page.module.scss
오호 scss 에서도 경로를 @로 쓸 수 있군요

나중에 이 형태로 리팩토링하는 것도 좋겠어요~👍

2024-10-06 15:42 UTC, merged