[chore/#20] axios 인스턴스 추가, react-query 설치
team-final/albaform pull request #21
Opened 2024-09-03 05:49 UTC by JiinSeok

resolved: #20

# 설명
로그인에 필요해서 먼저 설치했습니다.
인스턴스를 서버, 클라이언트로 나누었습니다.

서버: 데이터 처리, 인증
클라이언트: 사용자 상호작용

axios 함수들도 별도 파일에 담으려고 합니다

2024-09-03 07:36 UTC, clyde-yoon requested changes

2024-09-03 08:11 UTC, JuhyeokC commented on src/lib/api/axiosInstances.ts
> +  baseURL: "https://fe-project-albaform.vercel.app/7-4",
> 저는 baseUrl은 env에 설정해서 요기 인스턴스 만들때는
> 
> ```js
> const baseURL = process.env.NEXT~~
> ```
> 
> 하는게 더 좋을것같아요!

env 파일 생성해두셨으니 활용하는게 좋긴하겠네요!
전 안써봐서 어떻게 쓰는지 궁금합니다!

2024-09-03 09:45 UTC, JiinSeok commented on src/lib/api/axiosInstances.ts
> +  baseURL: "https://fe-project-albaform.vercel.app/7-4",
@clyde-yoon 좋아요 근데 이번 프로젝트에서 실제로 환경변수를 활용하려면 어떻게 할 수 있을까요? 저번에 어떻게 활용하셨어요?

2024-09-03 10:05 UTC, JiinSeok commented on src/lib/api/axiosInstances.ts
> +  withCredentials: true,
@clyde-yoon 감사합니다

2024-09-03 10:31 UTC, clyde-yoon commented on src/lib/api/axiosInstances.ts
> +  baseURL: "https://fe-project-albaform.vercel.app/7-4",
```js
NEXT_PUBLIC_API_URL=https://wikied-api.vercel.app/7-3
```

이렇게 env파일 만들어두고

```ts
const baseURL = process.env.NEXT_PUBLIC_API_URL;

const authApi: AxiosInstance = axios.create({
  baseURL,
  headers: {
    'Content-Type': 'application/json',
    Accept: 'application/json',
  },
});
```

axios파일에 이렇게작성해두었습니다

2024-09-03 13:08 UTC, clyde-yoon approved these changes

2024-09-06 02:37 UTC, gayeong0916 approved these changes

2024-09-06 02:37 UTC, merged