[feat/#14] Floating Button 컴포넌트 개발
team-final/albaform pull request #33
Opened 2024-09-03 14:29 UTC by gayeong0916

resolved: #ISSUE_NUMBER

# 설명
Floating Button 컴포넌트 개발

2024-09-03 14:38 UTC, JiinSeok commented on src/components/FloatingButton/CreateFormButton/CreateFormButton.tsx
> +//컴포넌트 immport
오타 발견

2024-09-03 16:27 UTC, JiinSeok commented
1. FloatingButton인데 z-index 스타일이 없어요. ㅠㅠ

2. 찾아 쓸 수 있는 이름으로 바꿔 보아요.

- OtherButton이라는 이름은 FloatingButton 폴더에서의 관점입니다. 스크랩 버튼을 달아야지 하는 사람이 찾기 어려울 것 같아요. 
- CreateFormButton은 FormCreatingButton으로 바꿀 수 있습니다. 그렇지만 이미 onClick으로 무슨 함수든 담을 수 있는데, FormCreating 말고 다른 버튼으로도 쓸 수 있다는 걸 이름만 봐서는 알 수 없네요. 모르고 새 버튼을 만들면 아까울 거 같아요.
- CircleFloatingButton, OvalFloatingButton이라면 파일 이름으로도 구별되니 Button 폴더에 담아도 좋을 것 같습니다.

2024-09-03 16:28 UTC, JiinSeok requested changes
1. FloatingButton인데 z-index 스타일이 없어요. ㅠㅠ

2. 찾아 쓸 수 있는 이름으로 바꿔 보아요.

- OtherButton이라는 이름은 FloatingButton 폴더에서의 관점입니다. 스크랩 버튼을 달아야지 하는 사람이 찾기 어려울 것 같아요.
- CreateFormButton은 FormButton 생성 함수 이름 같아서 FormCreatingButton으로 바꿀 수 있을 것 같아요. 
- 그렇지만 이미 onClick으로 무슨 함수든 담을 수 있는데, FormCreating 말고 다른 버튼으로도 쓸 수 있다는 걸 이름만 봐서는 알 수 없네요. 모르고 새 버튼을 만들 수도..
- CircleFloatingButton, OvalFloatingButton이라면 파일 이름으로도 구별되니 Button 폴더에 담아도 좋을 것 같습니다.!!!

2024-09-04 04:27 UTC, gayeong0916 commented on src/components/FloatingButton/CreateFormButton/CreateFormButton.tsx
> + */
넵!!!!

2024-09-06 09:37 UTC, JiinSeok commented on .husky/pre-commit
이거 주석처리 해제해주세용

2024-09-06 13:12 UTC, JuhyeokC approved these changes

2024-09-06 13:14 UTC, clyde-yoon approved these changes

2024-09-07 04:24 UTC, JiinSeok approved these changes

2024-09-07 04:27 UTC, merged