[feat/#80] 카카오맵 지도 개발
team-final/albaform pull request #91
Opened 2024-09-17 10:09 UTC by clyde-yoon

resolved: #ISSUE_NUMBER

# 설명
https://screeching-aster-4fb.notion.site/f476396fbd7246d09abff2b81ddd4526?pvs=4

개발 전 과정을 노션에 작성해보았습니다.

# 추가로

+ any타입이 필수적으로 필요합니다
+ 카카오앱키를 스크립트에 담아 브라우저에서 노출이 되는데 이를 숨기는 방법이 약간 필요할 것 같습니다
+ 디자인을 어떻게 하면 좋을지 얘기 나누고 싶습니다 !

2024-09-18 07:01 UTC, JuhyeokC commented
카카오맵 API 키 공개되는 건
발급받을 때 플랫폼 주소등록할 때 해당플랫폼 주소가 아니면 작동하지 않아서 문제 없을 겁니다!

2024-09-19 05:55 UTC, JiinSeok commented
키는 환경변수로 추가하면 될 것 같습니다 !!

2024-09-19 06:50 UTC, JiinSeok commented on src/components/KakaoMap/KaKaoMap.tsx
> +      window.kakao.maps.load(() => {
if (!window.kakao) 에러 처리 필요하지 않을까요?

2024-09-19 06:53 UTC, JiinSeok commented on src/components/KakaoMap/KaKaoMap.tsx
> +                const marker = new window.kakao.maps.Marker({
marker를 생성할 때 map를 넣는 것 같은데

`marker.setMap(map)` 이쪽에서 또 setMap(map)을 해야 하는지 궁금합니다.
`customOverlay.setMap(map)` 이쪽도 궁금합니다.

2024-09-19 07:01 UTC, JiinSeok commented on src/components/KakaoMap/KakaoMap.module.scss
> +.marker-text {
위와 맞춰서, overlay-text 또는 overlay-marker-text가 overlay 안의 텍스트 스타일이라는 뜻을 잘 알려줄 것 같습니다. (marker와 overlay가 어떤 관계인지)

2024-09-19 07:04 UTC, JiinSeok commented on src/components/KakaoMap/KaKaoMap.tsx
> +  }, [apiKey, location])
location.address 만 사용하기 때문에 location.address 로 바꾸는 게 렌더링을 최소화할 수 있을 것 같습니다.

2024-09-19 07:11 UTC, JiinSeok approved these changes

2024-09-19 07:26 UTC, JiinSeok requested changes

2024-09-19 07:26 UTC, JiinSeok commented on src/components/KakaoMap/KaKaoMap.tsx
> +import React, { useEffect, useRef, useState } from 'react'
'use client' 추가되어야 합니다

2024-09-19 07:35 UTC, JiinSeok commented
카카오앱키를 스크립트에 담아 브라우저에서 노출이 되는데 이를 숨기는 방법이 약간 필요할 것 같습니다
--> env.example에 있는 변수에 넣으면 어떤가요? 혹시 다른 이야기일까요??

2024-09-19 07:47 UTC, JiinSeok requested changes
useState, useEffect 빼고 서버 컴포넌트 - 정적 생성으로 바꾸어 api key 보호하는 것 제안합니다.

2024-09-19 07:47 UTC, JiinSeok commented on src/components/KakaoMap/KaKaoMap.tsx
> +const KakaoMap: React.FC<KakaoMapProps> = ({ apiKey, location }) => {
혹시 apiKey가 매번 바뀌는 건가요?

아니라면 props로 받지 않고, env에서 쓰면 좋을 것 같습니다. 

그런데 그렇게 바꿔도, "**클라이언트 사이드 코드에 포함된 API 키는 결국 사용자가 접근할 수 있으므로**"라고 하니, 서버 컴포넌트로 바꾸는 게 어떨까요?!
에러 처리 말고 useState가 쓰이지도 않고, 위치정보가 바뀌자마자 페이지가 새로 렌더링되어야 하는지 모르겠어서 괜찮을 것 같습니다. 에러 처리는 단순하게 if 필요한 데이터 없을 때, '지도 영역에 지도를 불러올 수 없습니다.' 띄우면 어떨까요?

또, API 키에 도메인 제한도 걸 수 있다고 하네요. 보안 강화 연습 겸 이것도 할 수 있을 것 같습니다.

-------
1. 카카오 개발자 사이트 접속: [카카오 개발자 사이트](https://developers.kakao.com/)에 로그인합니다.
2. 애플리케이션 선택: API 키를 발급받은 애플리케이션을 선택합니다.
3. 설정 메뉴로 이동: 좌측 메뉴에서 "앱 설정" -> "일반"을 클릭합니다.
4. Redirect URI 및 도메인 설정: "앱 키" 섹션에서 "JavaScript 키"를 찾습니다. 아래쪽에 "사이트 도메인" 항목이 있습니다. 여기서 API 키를 사용할 도메인을 추가합니다. 예를 들어, https://your-domain.com 또는 http://localhost:3000 (로컬 개발 시) 등의 도메인을 추가할 수 있습니다.
5. 변경 사항 저장: 모든 변경 사항을 저장합니다.

2024-09-19 08:02 UTC, JuhyeokC commented on src/components/KakaoMap/KaKaoMap.tsx
> +      window.kakao.maps.load(() => {
window 에 kakao 가 없을 경우 window 에 kakao 가 없다는 에러가 발생할 수 있어요!
옵셔널체이닝으로 예외처리를 할 수 있습니다요
```
const checkKakaomap = !!window?.kakao // window.kakao 가 undefined 일 경우 false
if ( checkKakaomap ) {
  window.kakao.maps.load(() => { ...
}
```

2024-09-19 08:05 UTC, JuhyeokC commented on src/components/KakaoMap/KakaoMap.module.scss
> +.marker-text {
지인님이 말씀하신 내용을 scss 스럽게 작성하는 법!
어떠신가요~
```
.custom-overlay {
  &-marker-text {
    ...속성
  }
}
```

2024-09-19 08:06 UTC, JiinSeok commented on src/components/KakaoMap/KaKaoMap.tsx
> +const KakaoMap: React.FC<KakaoMapProps> = ({ apiKey, location }) => {
앗 useRef 이제 봤는데 .current가 어떤 용도로 쓰이고 있는지 이해를 다 못해서 못 적었습니다 ㅜ
이 useRef가 필수라면 서버 컴포넌트로 못 바꾸겠지만, OAuth 키가 아니니 이 정도로 타협했다. 하면 될 것 같습니다.

2024-09-24 10:18 UTC, JiinSeok commented
@team-final/3pm 많은 관심 부탁 드려요

2024-09-25 07:01 UTC, merged